# Generated by Django 5.0.3 on 2024-03-06 10:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
        ('vaccine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='end_date',
        ),
        migrations.AddField(
            model_name='campaign',
            name='first_dose',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='forth_dose',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='second_dose',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='third_dose',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='vaccines',
        ),
        migrations.AddField(
            model_name='campaign',
            name='vaccines',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vaccine.vaccine'),
            preserve_default=False,
        ),
    ]
