# Generated by Django 5.0.3 on 2024-03-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_remove_campaign_end_date_campaign_first_dose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
