# Generated by Django 5.0.3 on 2024-03-06 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_campaign_campaign_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='first_dose',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='forth_dose',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='second_dose',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='third_dose',
        ),
    ]
