# Generated by Django 5.0.3 on 2024-03-06 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('campaign', '0004_remove_campaign_first_dose_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoseBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_dose_date', models.DateField(blank=True, null=True)),
                ('second_dose_date', models.DateField(blank=True, null=True)),
                ('third_dose_date', models.DateField(blank=True, null=True)),
                ('fourth_dose_date', models.DateField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userprofile')),
            ],
        ),
    ]
