# Generated by Django 5.0.3 on 2024-03-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_dosebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
