# Generated by Django 4.2.7 on 2024-03-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0002_vaccine_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
    ]
